server:
  port: 8082

spring:
  application:
    name: room-service

  datasource:
    url: jdbc:postgresql://localhost:5432/room_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: g7DoV5efMmZVdb23nYIYxPPHp1yngV6xGOdCeIN2AymRideshare2026SecureKeyForAllServices
  access-token-expiration: 900000   # 15 minutes
  refresh-token-expiration: 604800000  # 7 days